Thread thread = null;
SurfaceHolder surfaceHolder;
Canvas s_canvas;
#ifdef USE_BG_BUFFER
Canvas s_canvas_scale;
Bitmap s_bg_buffer;
#endif
mySound snd_player;
volatile int s_game_state = -1;
volatile int s_game_next_state = -1;
volatile int s_load_step_max = -1;
volatile int s_load_step = 0;
volatile int s_load_type = -1;
volatile boolean s_init_state = false;
volatile boolean s_exit_state = false;
volatile boolean s_skip_init_state = false;
boolean running = false;
boolean music_enable;
boolean sfx_enable;
myTouch s_touch;
balloonObject[] balloons;
bulletObject s_bullet;
mySprites s_gun;
int s_gun_angle;
int s_gun_fire;
Rect s_gameplay_rect = new Rect(Define.GAMEPLAY_X, Define.GAMEPLAY_Y, Define.GAMEPLAY_W, Define.GAMEPLAY_H);
myDialog s_dialog;
boolean s_showdialog = false;
String s_level = null;
int s_score = 0;
JSONArray s_questions = null;
String s_question = null;
char[] s_answer = null;
boolean[] s_answer_map = null;
boolean s_question_finish = false;
char[] s_answer_collected = null;
int s_highscore = 0;
myButtons btn_play;
myButtons btn_help;
myButtons btn_about;
myButtons btn_gamePause;
myButtons btn_close;
myButtons btn_resume;
myButtons btn_replay;
myButtons btn_mm;
myButtons btn_exit;
myButtons btn_music_on;
myButtons btn_music_off;
myButtons btn_sfx_on;
myButtons btn_sfx_off;
mySprites[] s_gameSprites;
long s_frameCount;
SharedPreferences s_ref;